version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9  # You can choose an image that suits your needs, e.g., Ubuntu, Python, etc.

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install nvm and Node.js
          command: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install 14
            nvm use 14

      - run:
          name: Check Node.js version
          command: |
            node -v

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
