version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9  # Replace with your preferred Docker image
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest  # Or your preferred test command

workflows:
  version: 2
  build:
    jobs:
      - build
